# Generated by Django 2.2 on 2021-01-25 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
    ]
