# Generated by Django 2.2 on 2021-01-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20210125_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
