# Generated by Django 2.2 on 2021-04-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20210419_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
